version: "3"

services:
  navicat:
    container_name: navicat
    image: navicat/navicatmonitor:3.0.1
    ports:
     - "3000:3000"
    networks: 
      - main-net
  
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    networks: 
      - main-net
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: ./../environments/postgres/.env.dev.local

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    networks: 
      - main-net
    env_file: ./../environments/pgadmin/.env.dev.local

volumes:
  db-data:

networks: 
  main-net: